on: [push]

jobs:
  start-selenoid:
    runs-on: ubuntu-latest
    name: Test SELENOID JOB
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - run: npm ci    
    - name: start selenoid
      uses: ./
    - name: is selenoid started?
      run: curl http://localhost:4444/status